name: Run Postman Tests

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 run-postman-tests:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Setup Node.js
     uses: actions/setup-node@v3
     with:
       node-version: '18'

   - name: Install Newman
     run: npm install -g newman

   - name: Run Postman Tests
     run: |
       newman run Week8-GitHubGraphQL.postman_collection.json \
       -e Week8-Env.postman_environment.json \
       --env-var "github_token=${{ secrets.GITHUB_TOKEN }}"
